# Generated by Django 4.2.29 on 2026-07-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecall',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Peça com Defeito', 'verbose_name_plural': 'Peças com Defeito'},
        ),
    ]
