# Generated by Django 4.2.29 on 2026-07-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecall_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Série'),
        ),
    ]
