# Generated by Django 4.2.29 on 2026-07-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_type_alter_invoice_return_code'),
        ('services', '0003_servicecall_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='destination_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_calls', to='invoices.invoice', verbose_name='NF de destino (entrada)'),
        ),
        migrations.AddField(
            model_name='servicecall',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='servicecall',
            name='returned_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade devolvida'),
        ),
        migrations.AddField(
            model_name='servicecall',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_calls', to='invoices.invoice', verbose_name='NF de origem (saída)'),
        ),
        migrations.AddField(
            model_name='servicecall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('attended', 'Atendido'), ('partial', 'Parcialmente devolvido'), ('returned', 'Devolvido')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servicecall',
            name='defect',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Defeito'),
        ),
        migrations.AlterField(
            model_name='servicecall',
            name='ticket_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número do chamado'),
        ),
    ]
