# Generated by Django 4.2.29 on 2026-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicecall_destination_invoice_servicecall_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecall',
            name='status',
            field=models.CharField(choices=[('new', 'Peça nova'), ('attended', 'Peça com defeito')], default='new', max_length=10, verbose_name='Status'),
        ),
    ]
