# Generated by Django 4.2.29 on 2026-07-08 21:45

from django.db import migrations


def migrate_status(apps, schema_editor):
    ServiceCall = apps.get_model('services', 'ServiceCall')
    ServiceCall.objects.filter(status='pending').update(status='new')
    ServiceCall.objects.filter(status__in=['partial', 'returned']).update(status='attended')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicecall_status'),
    ]

    operations = [
        migrations.RunPython(migrate_status),
    ]
