# Generated by Django 4.2.29 on 2026-07-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_migrate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='source_invoice_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='NF de saída (texto)'),
        ),
    ]
