# Generated by Django 4.2.29 on 2026-07-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('number', models.CharField(max_length=50, verbose_name='NF-e número')),
                ('return_code', models.CharField(max_length=50, verbose_name='Código de devolução')),
                ('volumes', models.PositiveIntegerField(default=1, verbose_name='Volumes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Nota fiscal',
                'verbose_name_plural': 'Notas fiscais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('product_code', models.CharField(max_length=50, verbose_name='Código do produto')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Nota fiscal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Item da nota fiscal',
                'verbose_name_plural': 'Itens da nota fiscal',
                'ordering': ['created_at'],
            },
        ),
    ]
