# Generated by Django 4.2.29 on 2026-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('outgoing', 'Saída'), ('incoming', 'Entrada')], default='outgoing', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='return_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código de devolução'),
        ),
    ]
