# Generated by Django 4.2.29 on 2026-07-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='return_refs',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='RETORNO REF. NF'),
        ),
    ]
