# Generated by Django 4.2.29 on 2026-07-08 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_servicecall_destination_invoice_servicecall_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_invoice_type_alter_invoice_return_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('service_call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecall', verbose_name='Peça com defeito')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Etiqueta de peça',
                'verbose_name_plural': 'Etiquetas de peças',
            },
        ),
        migrations.CreateModel(
            name='LabelSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('page_format', models.CharField(choices=[('A4', 'A4'), ('THERMAL_80MM', 'Bobina 80mm')], default='A4', max_length=20, verbose_name='Formato de página')),
                ('margin', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Margem (mm)')),
                ('font_size', models.PositiveIntegerField(default=11, verbose_name='Tamanho da fonte (pt)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_settings', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Configuração de etiqueta',
                'verbose_name_plural': 'Configurações de etiquetas',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('volume_index', models.PositiveIntegerField(verbose_name='Índice do volume')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='invoices.invoice', verbose_name='Nota fiscal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Etiqueta de romaneio',
                'verbose_name_plural': 'Etiquetas de romaneio',
                'ordering': ['volume_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoicelabel',
            constraint=models.UniqueConstraint(fields=('invoice', 'volume_index'), name='unique_volume_per_invoice'),
        ),
    ]
