# Generated by Django 4.2.29 on 2026-07-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('associations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='associations.association', verbose_name='Associação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Etiqueta de peça',
                'verbose_name_plural': 'Etiquetas de peças',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('volume_index', models.PositiveIntegerField(verbose_name='Índice do volume')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='invoices.invoice', verbose_name='Nota fiscal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Etiqueta de romaneio',
                'verbose_name_plural': 'Etiquetas de romaneio',
                'ordering': ['volume_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoicelabel',
            constraint=models.UniqueConstraint(fields=('invoice', 'volume_index'), name='unique_volume_per_invoice'),
        ),
    ]
