# Generated by Django 4.2.29 on 2026-07-03 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('page_format', models.CharField(choices=[('A4', 'A4'), ('THERMAL_80MM', 'Bobina 80mm')], default='A4', max_length=20, verbose_name='Formato de página')),
                ('margin', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Margem (mm)')),
                ('font_size', models.PositiveIntegerField(default=11, verbose_name='Tamanho da fonte (pt)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_settings', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Configuração de etiqueta',
                'verbose_name_plural': 'Configurações de etiquetas',
            },
        ),
    ]
